### ISSUE TITLE
What is SSL PEM if its not something generated?

### ISSUE THREAD

**Issue by drnic** [genesis-community/concourse-genesis-kit#2]
Re: https://github.com/genesis-community/concourse-genesis-kit#base-params

Running the kit I was first asked for `external_url`, so I assumed later I'd be asked for a static IP, so I mentally decided on `10.0.0.11` and therefore my external URL would be `ci.10-0-0-11.sslip.io`:

```
Required parameter: external_url

The external URL for concourse is the URL users will use to access it via their
web browser, or the fly CLI.

What is the external URL for concourse?
> ci.10-0-0-11.sslip.io
```

Next I was asked for "What is the SSL cert + key pair for Concourse". What is this? Is it something that should be generated by `safe`? Or something I'm supposed to get from `sslip.io` for the URL? AFAIK sslip.io uses a common root CA.

```
Secret data required -- will be stored in Vault under secret/bosh/1/concourse/ssl:combined

Concoure will be running on https by default, and as such, needs an SSL cert/key
specified. Please enter a combined pem-encoded private key + signed certificate.


What is the SSL cert + key pair for Concourse? (Enter <CTRL-D> to end)
----------------------------------------------------------------------
```

**Comment by geofffranks** [comment]
That's there since perhaps someone has a real domain they want concourse to be running on, with a real cert, vs a safe-generated one.

We should probably do something similar to what the CF kit does here: https://github.com/genesis-community/cf-genesis-kit/blob/master/hooks/params#L11-L34

**Comment by drnic** [comment]
Chatting with @dennisjbell we discussed that this could evolve into subkits to perform either:

* generate internal certs
* provide external cert (like above) with or without a custom root

**Comment by geofffranks** [comment]
👍 We should probably also disable non-https in the kit after doing ^^
