### ISSUE TITLE
Worker VM Type Defaults

### ISSUE THREAD

**Issue by Proplex** [genesis-community/concourse-genesis-kit#23]
We should probably discuss the idea of setting a default worker VM type (or updating the wizard to let users define one). Otherwise a default `genesis new` will most likely fail because the default VM type is typically small.

I'd be more than happy to implement the solution chosen.

**Comment by jhunt** [comment]
Let's just introduce a new default for the worker, in the kit yamls.  Call it `concourse` and advise (via MANUAL.md or README.md, wherever cloud-config stuff is currently) that it should be a certain size (ephemeral and RAM)

**Comment by jhunt** [comment]
Fixed in #28
