### ISSUE TITLE
Could the kit autodetect Azure from `bosh env`?

### ISSUE THREAD

**Issue by drnic** [genesis-community/concourse-genesis-kit#3]
```
$ bosh2 env --tty | grep CPI
CPI       google_cpi
```

Could `genesis new` use this information to determine if its Azure CPI or not, rather than a manual prompt?

**Comment by drnic** [comment]
I think I understand this is a limitation of the kit/subkit YAML -> UI system. I'll close this until I think of a productive issue/PR.

**Comment by geofffranks** [comment]
@drnic I've been toying with the idea of dropping the azure subkits for everything but CF. In most of the kits, the azure component just overrides AZs so you don't need to define multiple unused AZs in your cloud config. Having them in there seems to lead to some confusion though.

On the CF one, however it's necessary, as it enables a feature in diego to auto-detect the fault-domain for cells.
